version: '3.8'
services:
  server:
    container_name: crtest
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - "5016:5000"
    restart: unless-stopped